apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ci-helper-app-brrf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ci-helper-app-brrf
    app.kubernetes.io/part-of: ci-helper-app
  name: ci-helper-app-brrf5vf4
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ci-helper-app-brrf
    weight: 100
status: {}
