apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ci-helper-app-brrf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ci-helper-app-brrf
    app.kubernetes.io/part-of: ci-helper-app
  name: ci-helper-app-brrf
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ci-helper-app-brrf
status:
  loadBalancer: {}
